name: Build

on:
  push:
    branches: []
  pull_request:
    branches: []

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always

jobs:
  all:
    name: All

    strategy:
      matrix:
        target:
        - x86_64-unknown-linux-gnu
        include:
        - target: x86_64-unknown-linux-gnu
          os:     ubuntu-latest

    runs-on: ${{matrix.os}}

    env:
      RUSTFLAGS: "-D warnings"

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
        components: clippy

    - name: Info
      run: |
        rustup --version
        cargo --version
        cargo clippy --version

    - name: Apt Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ gcc git make nasm ninja-build

    - name: Build
      run: |
        cargo build --bin pxsum --target ${{ matrix.target }}
        cargo build --bin pxsum --release --target ${{ matrix.target }}

    - name: Clippy
      run: |
        cargo clippy --release --target ${{ matrix.target }}

    - name: Test
      run: |
        cargo test --target ${{ matrix.target }}
        cargo test --release --target ${{ matrix.target }}
